apiVersion: batch/v1
kind: Job
metadata:
  name: headstart-migration-job
spec:
  template:
    spec:
      containers:
      - name: migration
        image: headstart/backend:latest
        command: ["alembic", "upgrade", "head"]
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: headstart-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: headstart-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: headstart-config
              key: POSTGRES_DB
      restartPolicy: Never
